/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <iostream>
/* Header for class com_gradle_test_JniTest */

#ifndef _Included_com_gradle_test_JniTest
#define _Included_com_gradle_test_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gradle_test_JniTest
 * Method:    start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gradle_test_JniTest_start(JNIEnv *env, jobject) {
	printf("\n Call from: Java_com_gradle_test_JniTest_start");
	return;
}

#ifdef __cplusplus
}
#endif
#endif
